name: K6 load test

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  protocol:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v4

      - name: step 2 - setup k6
        uses: grafana/setup-k6-action@v1

      - name: step 3 - run k6 load test
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./tests/1_health.js
            ./tests/2_create_user.js
            ./tests/3_login_user.js
            ./tests/4_retrieve_user.js
            ./tests/5_update_user.js
            ./tests/6_change_password.js
            ./tests/7_create_note.js
            ./tests/8_create_another_note.js
            ./tests/9_get_all_notes.js
            ./tests/10_get_note.js
            ./tests/11_update_note.js
            ./tests/12_update_completeness_note.js
            ./tests/13_delete_note.js
            ./tests/14_logout_user.js
            ./tests/15_login_user_after_logout.js
            ./tests/16_delete_user.js
          parallel: false # optional: run tests in parallel (default: false)
          fail-fast: false # optional: fail the step early if any test fails (default: true). Need to configure to execute all files and generate report for each
        
      - run: ls & mkdir reports & mv report.html reports      
      
      - name: step 4 - upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: report
          path: reports

